kube-prometheus-stack:
  grafana:
    enabled: false
    forceDeployDatasources: true
    forceDeployDashboards: true
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
  alertmanager:
    config:
      global:
        resolve_timeout: 5m
        slack_api_url: $(SLACK_API_URL)
      route:
        group_by:
          - namespace
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'slack'
        routes:
          - receiver: 'slack'
            matchers:
              - alertname: Watchdog
      receivers:
        - name: slack
          slack_configs:
            - channel: '#kubernetes-alerts'
              send_resolved: true
    ## Optionally specify extra environment variables to add to alertmanager container
    extraEnv:
      - name: SLACK_API_URL
        valueFrom:
          secretKeyRef:
            name: slack-webhook-secret
            key: slack_api_url