source "proxmox-iso" "debian-cloud-init" {
  proxmox_url              = "https://${var.proxmox_ip}:8006/api2/json"
  username                 = "${var.proxmox_user}"
  password                 = "${var.proxmox_password}"
  node                     = "${var.proxmox_node}"
  insecure_skip_tls_verify = true

  iso_file             = "local:iso/${var.iso_file}"
  iso_checksum         = "${var.iso_checksum}"
  iso_storage_pool     = "local"
  vm_name              = "debian-${var.iso_version}-template"
  template_description = "Debian ${var.iso_version} Cloud-init template, generated by Packer on ${timestamp()}"
  vm_id                = "${var.vm_id}"
  os                   = "l26"
  memory               = "${var.memory}"
  cores                = "${var.cores}"
  sockets              = "${var.sockets}"
  machine              = "pc"
  bios                 = "seabios"
  cpu_type             = "host"
  qemu_agent           = true

  network_adapters {
    model  = "virtio"
    bridge = "vmbr0"
  }

  disks {
    type         = "scsi"
    storage_pool = "local-zfs"
    disk_size    = "${var.disk_size}"
    ssd          = true
    discard      = true
  }

  scsi_controller = "virtio-scsi-pci"

  ssh_username = "${var.ssh_username}"
  ssh_password = "${var.ssh_password}"
  ssh_timeout  = "20m"

  cloud_init              = true
  cloud_init_storage_pool = "local-zfs"

  http_directory = "http"
  boot_wait      = "10s"
  boot_command   = ["<esc><wait>auto url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<enter>"]
  unmount_iso    = true

  tags = "template"
}
