grafana:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - &host grafana.thehackshop.com
    tls:
      - secretName: grafana-general-tls
        hosts:
          - *host
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring-system
    datasources:
      enabled: true
      searchNamespace: monitoring-system
  envFromSecret: grafana-secrets
  grafana.ini:
    server:
      root_url: https://grafana.thehackshop.com
