---
- name: Copying kubeconfig from {{ hostvars[groups[group_name_servers | default('servers')][0]]['ansible_hostname'] }}
  ansible.builtin.fetch:
    src: "{{ ansible_user_dir }}/.kube/config"
    dest: ~/.kube/config
    flat: true
  when: ansible_hostname == hostvars[groups[group_name_servers | default('servers')][0]]['ansible_hostname']
