longhorn:
  ingress:
    enabled: true
    host: longhorn.thehackshop.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls: true
  metrics:
    ServiceMonitor:
      enabled: true
  defaultSettings:
    allowEmptyDiskSelectorVolume: true
    # backupTarget: s3://backupbucket@us-east-1/backupstore
    # backupTargetCredentialSecret: minio-secret
    # createDefaultDiskLabeledNodes: true
    # defaultDataPath: /var/lib/longhorn-example/
    # replicaSoftAntiAffinity: false
    # storageOverProvisioningPercentage: 600
    # storageMinimalAvailablePercentage: 15
    # upgradeChecker: false
    # defaultReplicaCount: 2
    # defaultDataLocality: disabled
    # defaultLonghornStaticStorageClass: longhorn-static-example
    # backupstorePollInterval: 500
    # taintToleration: key1=value1:NoSchedule; key2:NoExecute
    # systemManagedComponentsNodeSelector: "label-key1:label-value1"
    # priorityClass: high-priority
    # autoSalvage: false
    # disableSchedulingOnCordonedNode: false
    # replicaZoneSoftAntiAffinity: false
    # replicaDiskSoftAntiAffinity: false
    # volumeAttachmentRecoveryPolicy: never
    # nodeDownPodDeletionPolicy: do-nothing
    # guaranteedInstanceManagerCpu: 15
    # orphanAutoDeletion: false