openspeedtest:
  replicaCount: 2
  ingress:
    enabled: true
    hosts:
      - host: speedtest.thehackshop.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls:
      - secretName: speedtest-tls
        hosts:
          - speedtest.thehackshop.com
  service:
    type: ClusterIP
    port: 3000