name: Build Templates

on:
  push:
    branches:
      - main
    paths:
      - 'packer/**'
  workflow_dispatch:

env:
  PROXMOX_NODE: ${{ secrets.PROXMOX_NODE }}
  PROXMOX_USER: ${{ secrets.PROXMOX_USER }}
  PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}
  PROXMOX_IP: ${{ secrets.PROXMOX_IP }}
  PACKER_SSH_USER: ${{ secrets.PACKER_SSH_USER }}
  PACKER_SSH_PASSWORD: ${{ secrets.PACKER_SSH_PASSWORD }}

jobs:
  run-script:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./packer/debian/12-bookworm

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Configure Packer Variables Values
        run: |
          cat <<EOF > ../../values.auto.pkrvars.hcl
          ssh_username = "${PACKER_SSH_USER}"
          ssh_password = "${PACKER_SSH_PASSWORD}"
          proxmox_ip = "${PROXMOX_IP}"
          proxmox_user = "${PROXMOX_USER}"
          proxmox_password = "${PROXMOX_PASSWORD}"
          proxmox_node = "${PROXMOX_NODE}"
          EOF

      - name: Run Packer init
        run: |
          echo "Running Packer init"
          packer init .

      - name: Run Debian 12 Bookworm build
        run: |
          echo "Running Debian 12 Bookworm build"
          ./build.sh