---
- name: Deploy metallb pool
  ansible.builtin.include_tasks: metallb.yaml
  tags: metallb

- name: Remove tmp directory used for manifests
  ansible.builtin.file:
    path: /tmp/k3s
    state: absent
